FROM python:3.8-slim-bullseye

COPY . .

RUN pip install --user poetry
ENV PATH="${PATH}:/root/.local/bin"
RUN poetry export -f requirements.txt -o requirements.txt --without-hashes

RUN pip install -r requirements.txt

ENTRYPOINT [ "python", "-m", "src.AvatarServer"]
